@c This is part of the Emacs manual.
@c Copyright (C) 1985, 1986, 1987, 1993, 1994 Free Software Foundation, Inc.
@c See file emacs.texi for copying conditions.
@node MS-DOS, Manifesto, Antinews, Top
@appendix MS-DOS Issues
@cindex MS-DOG
@cindex MS-DOS

  This section briefly describes the peculiarities of using Emacs under
the MS-DOS ``operating system'' (also known as ``MS-DOG'').

  MS-DOS normally uses a backslash, @samp{\}, to separate name units
within a file name, instead of the slash used on other systems.
Emacs on MS-DOS permits use of either slash or backslash.

  On MS-DOS, file names are case-insensitive and limited to eight
characters, plus optionally a period and three more characters.  Emacs
does not know about this limitation; it is up to you to specify valid
file names.  Excess characters before or after the period are generally
ignored.

  Display on MS-DOS in Emacs 19.26 does not support menus or multiple
fonts.  Support for multiple faces that specify different colors
should be added in version 19.27.

  Emacs on MS-DOS does support a mouse (on the default terminal only).
The mouse commands work as documented, aside from those that try to use
menus.  @xref{Mouse Commands}.

  Because MS-DOS is a single-process ``operating system'', asynchronous
subprocesses are not available.  In particular, Shell mode and its
derivatives do not work.  Compilation under Emacs with @kbd{M-x compile}
does work, but the compiler runs synchronously; you cannot do any more
editing until the compilation finishes.

  When you run a subprocess synchronously on MS-DOS, make sure the
program terminates and does not try to read keyboard input.  If the
program does not terminate on its own, you will be unable to terminate
it, because MS-DOS provides no general way to terminate a process.

